# Generated by Django 5.1.2 on 2024-10-20 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="Enter customer's first name", max_length=100)),
                ('last_name', models.CharField(help_text="Enter customer's last name", max_length=100)),
                ('email', models.EmailField(help_text="Enter customer's email address", max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, help_text="Enter customer's phone number", max_length=20)),
                ('address', models.TextField(blank=True, help_text="Enter customer's address")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
            },
        ),
    ]
